import type { RainEvidence } from "./types";

/**
 * Sample evidence for 17 September 2026.
 *
 * TEMPORARY: replace with a Supabase query against `rain_evidence`
 * (same column names) once the ingestion pipeline exists.
 */
export const OBSERVATION_DATE = "2026-09-17";

export const MOCK_EVIDENCE: RainEvidence[] = [
  {
    id: "ev-001",
    observation_date: OBSERVATION_DATE,
    event_time: "2026-09-17T09:20:00+05:30",
    place: "Jaipur",
    district: "Jaipur",
    latitude: 26.9124,
    longitude: 75.7873,
    rain_observed: true,
    forecast_status: "rain_expected",
    confidence: 0.92,
    source_url: null,
    source_type: "social_post",
    original_or_repost: "original",
    verification_status: "verified",
  },
  {
    id: "ev-002",
    observation_date: OBSERVATION_DATE,
    event_time: "2026-09-17T07:05:00+05:30",
    place: "Jodhpur",
    district: "Jodhpur",
    latitude: 26.2389,
    longitude: 73.0243,
    rain_observed: true,
    forecast_status: "unknown",
    confidence: 0.71,
    source_url: null,
    source_type: "news",
    original_or_repost: "original",
    verification_status: "verified",
  },
  {
    id: "ev-003",
    observation_date: OBSERVATION_DATE,
    event_time: null,
    place: "Udaipur",
    district: "Udaipur",
    latitude: 24.5854,
    longitude: 73.7125,
    rain_observed: false,
    forecast_status: "rain_expected",
    confidence: 0.64,
    source_url: null,
    source_type: "weather_api",
    original_or_repost: "unknown",
    verification_status: "verified",
  },
  {
    id: "ev-004",
    observation_date: OBSERVATION_DATE,
    event_time: "2026-09-17T05:40:00+05:30",
    place: "Kota",
    district: "Kota",
    latitude: 25.2138,
    longitude: 75.8648,
    rain_observed: true,
    forecast_status: "rain_expected",
    confidence: 0.55,
    source_url: null,
    source_type: "social_post",
    original_or_repost: "repost",
    verification_status: "pending",
  },
  {
    id: "ev-005",
    observation_date: OBSERVATION_DATE,
    event_time: null,
    place: "Bikaner",
    district: "Bikaner",
    latitude: 28.0229,
    longitude: 73.3119,
    rain_observed: false,
    forecast_status: "no_rain_expected",
    confidence: 0.8,
    source_url: null,
    source_type: "weather_api",
    original_or_repost: "unknown",
    verification_status: "verified",
  },
  {
    id: "ev-006",
    observation_date: OBSERVATION_DATE,
    event_time: "2026-09-17T11:15:00+05:30",
    place: "Ajmer",
    district: "Ajmer",
    latitude: 26.4499,
    longitude: 74.6399,
    rain_observed: true,
    forecast_status: "rain_expected",
    confidence: 0.88,
    source_url: null,
    source_type: "social_post",
    original_or_repost: "original",
    verification_status: "verified",
  },
  {
    id: "ev-007",
    observation_date: OBSERVATION_DATE,
    event_time: null,
    place: "Jaisalmer",
    district: "Jaisalmer",
    latitude: 26.9157,
    longitude: 70.9083,
    rain_observed: false,
    forecast_status: "no_rain_expected",
    confidence: 0.77,
    source_url: null,
    source_type: "weather_api",
    original_or_repost: "unknown",
    verification_status: "verified",
  },
  {
    id: "ev-008",
    observation_date: OBSERVATION_DATE,
    event_time: "2026-09-17T08:50:00+05:30",
    place: "Bhilwara",
    district: "Bhilwara",
    latitude: 25.3407,
    longitude: 74.6313,
    rain_observed: true,
    forecast_status: "rain_expected",
    confidence: 0.61,
    source_url: null,
    source_type: "social_post",
    original_or_repost: "original",
    verification_status: "pending",
  },
  {
    id: "ev-009",
    observation_date: OBSERVATION_DATE,
    event_time: null,
    place: "Alwar",
    district: "Alwar",
    latitude: 27.5665,
    longitude: 76.6250,
    rain_observed: false,
    forecast_status: "rain_expected",
    confidence: 0.58,
    source_url: null,
    source_type: "weather_api",
    original_or_repost: "unknown",
    verification_status: "verified",
  },
  {
    id: "ev-010",
    observation_date: OBSERVATION_DATE,
    event_time: "2026-09-17T06:30:00+05:30",
    place: "Mount Abu",
    district: "Sirohi",
    latitude: 24.5925,
    longitude: 72.7156,
    rain_observed: true,
    forecast_status: "rain_expected",
    confidence: 0.95,
    source_url: null,
    source_type: "news",
    original_or_repost: "original",
    verification_status: "verified",
  },
  {
    id: "ev-011",
    observation_date: OBSERVATION_DATE,
    event_time: null,
    place: "Barmer",
    district: "Barmer",
    latitude: 25.7521,
    longitude: 71.3967,
    rain_observed: false,
    forecast_status: "no_rain_expected",
    confidence: 0.83,
    source_url: null,
    source_type: "weather_api",
    original_or_repost: "unknown",
    verification_status: "verified",
  },
  {
    id: "ev-012",
    observation_date: OBSERVATION_DATE,
    event_time: "2026-09-17T10:10:00+05:30",
    place: "Bharatpur",
    district: "Bharatpur",
    latitude: 27.2152,
    longitude: 77.4977,
    rain_observed: true,
    forecast_status: "rain_expected",
    confidence: 0.69,
    source_url: null,
    source_type: "social_post",
    original_or_repost: "repost",
    verification_status: "pending",
  },
];
